version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-app
    environment:
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
    ports:
      - "8081:8081"
    networks:
      - Kafka-network
    depends_on:
      - mongo-db
      - kafka
      - localstack
    restart: on-failure

  mongo-db:
    image: mongo:6.0
    container_name: mymongo
    ports:
      - "27017:27017"
    networks:
      - Kafka-network
    volumes:
      - mongo-volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=mydb


  kafka:
    # Use Confluent CP Kafka image which is widely available on Docker Hub
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      # internal listener for inter-broker and other container clients
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      # advertise both an internal name (kafka) and an external address (localhost:9093) for host clients
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,OUTSIDE://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=1
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - Kafka-network
    depends_on:
      - zookeeper
    restart: unless-stopped

  zookeeper:
    image: zookeeper:3.8.1
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - Kafka-network
    restart: unless-stopped

  localstack:
    image: localstack/localstack:2.2
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
    volumes:
      - localstack-volume:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - Kafka-network
    restart: unless-stopped

networks:
  Kafka-network:

volumes:
  mongo-volume:
  localstack-volume: